version: '3'

services:

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: unless-stopped
    volumes:
      - ./deploy/mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883

  api:
    build: .
    container_name: rs-graphql
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - ADDRESS=0.0.0.0:8080
    command: bash -c "cargo watch -w src -w Cargo.toml -x run"
    ports:
      - 8080:8080
